// src/app/App.tsx
import { Hero } from "./components/Hero";
import { Services } from "./components/Services";
import { AIFeatures } from "./components/AIFeatures";
import { About } from "./components/About";
import { CTA } from "./components/CTA";
import { Footer } from "./components/Footer";

export default function App() {
  return (
    <div className="min-h-screen bg-white">
      <Hero />
      <AIFeatures />
      <Services />
      <About />
      <CTA />
      <Footer />
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import Hero from './components/Hero.vue'
import AIFeatures from './components/AIFeatures.vue'
import Services from './components/Services.vue'
import About from './components/About.vue'
import CTA from './components/CTA.vue'
import Footer from './components/Footer.vue'
</script>

<template>
  <div class="min-h-screen bg-white">
    <Hero />
    <AIFeatures />
    <Services />
    <About />
    <CTA />
    <Footer />
  </div>
</template>
